[project]
name = "phidata"
version = "1.10.0"
description = "A toolkit for building applications using OSS"
requires-python = ">=3.7"
readme = "README.md"
authors = [
  {name = "Ashpreet Bedi", email = "ashpreet@phidata.com"}
]

dependencies = [
  "boto3",
  "docker",
  "gitpython",
  "httpx",
  "kubernetes",
  "pydantic",
  "pydantic-settings",
  "python-dotenv",
  "pyyaml",
  "rich",
  "tomli",
  "typer",
  "typing-extensions",
]

[project.optional-dependencies]
dev = [
    "mypy",
    "black",
    "pytest",
    "ruff",
    "types-pyyaml",
]
aws = [
    "boto3",
]

#[project.scripts]
#phi = "phi.cli.cli_app:cli"

[project.urls]
homepage = "https://phidata.com"
documentation = "https://docs.phidata.com"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["phidata", "phi"]

[tool.black]
line-length = 110
exclude = [
  "phienv*",
]

[tool.ruff]
line-length = 110
exclude = [
  "phienv*",
  "phidata",
]
# Ignore `F401` (import violations) in all `__init__.py` files
[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.mypy]
plugins = [
  "pydantic.mypy"
]
check_untyped_defs = true
no_implicit_optional = true
warn_unused_configs = true
exclude = [
  "phienv*",
  "phidata",
]

[[tool.mypy.overrides]]
module = [
  "setuptools.*",
  "docker.*",
]
ignore_missing_imports = true
