name: Main Validation

on:
  push:
    branches:
      - '*'  # Run on all branches

jobs:
  style-check:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
      fail-fast: true  # Stop all matrix jobs if one fails

    defaults:
      run:
        working-directory: libs/agno

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade \
            pip setuptools wheel \
            ruff mypy pytest types-pyyaml
          pip install --no-deps -r requirements.txt
      - name: Ruff format
        run: |
          ruff format .
      - name: Ruff check
        run: |
          ruff check .
      - name: Mypy
        run: |
          mypy .

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Run dev setup
        working-directory: .
        run: |
          ./scripts/dev_setup.sh
      
      # Check for file changes
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41

      # Run OpenAI specific tests if relevant files changed
      - name: Run OpenAI tests
        if: contains(steps.changed-files.outputs.all_changed_files, 'libs/agno/models/openai')
        working-directory: .
        run: |
          source .venv/bin/activate
          python -m pytest ./libs/agno/tests/integration/models/openai

      # Run Google specific tests if relevant files changed
      - name: Run Google tests
        if: contains(steps.changed-files.outputs.all_changed_files, 'libs/agno/models/google')
        working-directory: .
        run: |
          source .venv/bin/activate
          python -m pytest ./libs/agno/tests/integration/models/google

      # TODO: Add tests for other models

      # Run all other integration tests
      - name: Run remaining integration tests
        working-directory: .
        run: |
          source .venv/bin/activate
          python -m pytest --ignore=./libs/agno/tests/integration/models ./libs/agno/tests/integration
